### ISSUE TITLE
Add docs for multidim-interop and update readme

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#101]

**Comment by p-shahi** [comment]
You might have already had this in mind but perhaps we can repurpose the [design doc](https://github.com/libp2p/test-plans/blob/master/DESIGN.md) for this, as well as reference https://github.com/libp2p/test-plans/issues/103 in the readme for discoverability.

**Comment by thomaseizinger** [comment]
The description of the repo also still mentions testground.

**Comment by p-shahi** [comment]
Partially fulfilled by https://github.com/libp2p/test-plans/pull/128

**Comment by p-shahi** [comment]
done in https://github.com/libp2p/test-plans/pull/117
