### ISSUE TITLE
add tests for hole punching

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#126]
We should have tests to make sure that hole-punching through a NAT / firewall works. This test would mainly make sure that the DCUtR protocol is doing its job in coordinating the hole punch attempt.

This test would be especially valuable if it can be used to hole punch using different transports. That way, we can make sure that hole punching works on both TCP and QUIC, for example.

Main challenge: We need to find a way to model a NAT, so that we actually have something to punch through.

This test would build on (and probably replace) the Circuit v2 test (#116), similar to how the handshake RTT test is replacing the ping test.

**Comment by p-shahi** [comment]
Does this duplicate https://github.com/libp2p/test-plans/issues/21

If so let's close one or the other

**Comment by thomaseizinger** [comment]
Given that we don't even have https://github.com/libp2p/test-plans/issues/116 yet, does it make sense to start that? Now that `rust-libp2p` has full hole-punching support for QUIC as well, I'd really like some automated tests for that.

> Main challenge: We need to find a way to model a NAT, so that we actually have something to punch through.

Similarly to how @mxinden used terraform for the perf tests, I think we could provision a network with a NAT on AWS and then deploy the nodes there and run the tests.

**Comment by marten-seemann** [comment]
Cross-posting here, I added some pointers for a dockerized NAT setup in https://github.com/libp2p/test-plans/issues/116#issuecomment-1602474996.

**Comment by thomaseizinger** [comment]
For all interested parties, there is now a PR at https://github.com/libp2p/test-plans/pull/304.
