### ISSUE TITLE
dht test plan is using outdated `testground/sdk-go`

### ISSUE THREAD

**Issue by nonsense** [libp2p/test-plans#13]
@sujith2s raised that the libp2p/dht test plan doesn't compile with the latest `sdk-go`. Ideally we should refactor it, and make it compatible, so that folks can run it with latest version of Testground.

---

copied from https://github.com/testground/testground/issues/1169

I tried the same for /libp2p/dht test case as well, updated the sdk-go and tried to run the test. 
without updating the sdk-go, i am getting the same error as ping .

cd $TESTGROUND_HOME/plans/libp2p/dht
go get github.com/testground/sdk-go@master

command
-----------
testground run single --plan libp2p/dht --testcase find-peers --builder docker:go --runner local:docker --run-cfg log_level=info --instances=20 --wait

error
------
for dht test case i am still getting this error after updating the sdk-go.
@nonsense can you show some lights on it, how to solve it.

# github.com/libp2p/test-plans/dht/utils
utils/identifiers.go:28:23: ri.Client.SignalAndWait undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/identifiers.go:46:11: ri.Client.MustPublishSubscribe undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:59:23: s.stager.ri.Client.SignalEntry undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:64:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:64:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:72:21: s.stager.ri.Client.MustBarrier undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:73:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:73:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:79:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:79:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:79:28: too many errors

Nov  7 05:53:51.727593	INFO	build failed	{"plan": "dht", "groups": ["single"], "builder": "docker:go", "error": "docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2"}

>>> Result:

docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2

Thanks in advance.

**Comment by p-shahi** [comment]
Moving dht tests out of the repo see https://github.com/libp2p/test-plans/pull/129
