### ISSUE TITLE
Make build cache bucket public

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#132]
@galargh could we make the build cache publicly readable? This would allow forks to still benefit from the cache.

**Comment by MarcoPolo** [comment]
Context here: https://github.com/libp2p/test-plans/pull/121#discussion_r1103314329

**Comment by thomaseizinger** [comment]
Should we then set it unconditionally or still always pass the name and region in?

In other words, if you pass credentials, write to the cache, otherwise just read from it.

**Comment by MarcoPolo** [comment]
default to the public name/region but allow you to override.

**Comment by galargh** [comment]
Done through https://github.com/pl-strflt/tf-aws-bootstrap/pull/1

BTW, these are the options for global bucket ACLs - https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

I set it to `public-read`

**Comment by thomaseizinger** [comment]
What is the name of the bucket? I'd like to set it as the default for our action to have PRs also use this cache.

**Comment by galargh** [comment]
It's https://github.com/pl-strflt/tf-aws-bootstrap/blob/cfe94aae3e3b7f7ea099f14f834dc1e5aac626df/libp2p.tf#L2

**Comment by galargh** [comment]
@MarcoPolo I updated the policy again - https://github.com/pl-strflt/tf-aws-bootstrap/commit/d31fd08a4574bbe1d3104ccc81a72c994141c248. Apparently, the ready-made one doesn't involve Get on objects 🤷

**Comment by thomaseizinger** [comment]
> http://s3.amazonaws.com/libp2p-by-tf-aws-bootstrap/buildCacheblobs/sha256:ffcc0b88f0be9d496e2dffcdb451a8c0e42b8f31b6807b31985570a532c5ecbd gives me access denied.

Just tried, this one works now!

**Comment by MarcoPolo** [comment]
ty! I think we can close this.
