### ISSUE TITLE
JS test references "quic" in a few places

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/test-plans#142]
This snippet doesn't seem right: https://github.com/libp2p/test-plans/blob/master/multidim-interop/js/v0.41/test/ping.spec.ts#L79-L81

In general, we can't support `quic` at all (only `webtransport`) so I am surprised to see it referenced here.

**Comment by p-shahi** [comment]
done in https://github.com/libp2p/js-libp2p/pull/1807
