### ISSUE TITLE
Bring back zig-libp2p

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/test-plans#169]
We just had the following interop failure on a PR that only deprecates functions and changes otherwise no functionality: https://github.com/libp2p/rust-libp2p/actions/runs/4746349161/attempts/1

cc @MarcoPolo

**Comment by MarcoPolo** [comment]
Oh no! Happy to remove for now and add them back once I debug.

**Comment by MarcoPolo** [comment]
fyi, I have a theory about the issue here, but haven't had time yet to push the changes: https://github.com/MarcoPolo/zig-libp2p/pull/1. Opening this again to keep track of putting zig-libp2p back in here :)

**Comment by MarcoPolo** [comment]
My theory is correct, but my fix didn't fix it apparently: https://github.com/libp2p/test-plans/actions/runs/4852666077

The failed attempt was running on a broadwell chip (8 years old!)

**Comment by MarcoPolo** [comment]
fixed in https://github.com/MarcoPolo/zig-libp2p/pull/3
