### ISSUE TITLE
zig-libp2p interop failure

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#227]
https://github.com/libp2p/go-libp2p/actions/runs/5437074878/jobs/9978115486?pr=2400

I haven't looked into it in detail, but might be use of an uninitialized buffer?

**Comment by MarcoPolo** [comment]
Compose stdout adds a line break to the stdout which breaks the very rudimentary parsing of the timings. Fix in PR here: https://github.com/libp2p/test-plans/pull/224

**Comment by marten-seemann** [comment]
Are you sure this fixes the issue? There seems to be an actual error here, no?

```
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | 
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | debug: Total buf size: 0 buffer count: 0
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | 
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | error: Wrong response: 0000000000000000000000000000000000000000000000000000000000000000
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | error: Wrong response: 
zig-v0_0_1_x_go-libp2p-head__quic-v1_-dialer-1    | debug: MSS  handling event: initiator=true

**Comment by MarcoPolo** [comment]
Red herring. Ping succeeded, I just didn't handle the case where I get an event with no data in ping fix for that is here: https://github.com/MarcoPolo/zig-libp2p/pull/7
