### ISSUE TITLE
Getting close to the 14 GB Actions limit

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#229]
I think we're getting dangerously close to GitHub Action's 14 GB storage limit on action runners. We should print out stats for the sizes of each image so we can get a feel for the total usage and where it makes sense to trim.

**Comment by achingbrain** [comment]
I see `ENOSPC: no space left on device` errors in when running multidim interop  tests in CI 😢 

Eg: https://github.com/libp2p/js-libp2p/actions/runs/5643526691/job/15285746637

**Comment by MarcoPolo** [comment]
Js will hit this issue more often. @galargh how do we get js-libp2p to run on self hosted runners?

**Comment by galargh** [comment]
We did get JS on self-hosted in https://github.com/libp2p/js-libp2p/pull/1891.
