### ISSUE TITLE
js-libp2p webrtc tests flaky

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#235]
Related: https://github.com/libp2p/js-libp2p/issues/1846

There's a lot of stuff in the stack, so this needs investigation as to what is being flaky. Is it:
- js-libp2p
- js-libp2p-webrtc
- js-libp2p circuitV2
- js-libp2p p2p-circuit transport
- Browser itself
- Something else?

My hope is that it's not the browser as everything else is easier to fix. Maybe a very simple non-js-libp2p browser only interop test would be a good way to test if the browser is at fault.

**Comment by MarcoPolo** [comment]
cc @maschad

**Comment by MarcoPolo** [comment]
I would use https://playwright.dev directly, avoiding Aegir and playwright-test.

I'll probably do this at some point this week, but if you have bandwidth and it seems interesting, let me know and you can take.

**Comment by maschad** [comment]
Good point, Thanks for clarifying. I will take a look into it this week.

**Comment by MarcoPolo** [comment]
Sounds good. Let's sync up when you get a chance.

**Comment by maschad** [comment]
>  Maybe a very simple non-js-libp2p browser only interop test would be a good way to test if the browser is at fault.

So after syncing with @MarcoPolo , we decided to setup a very simple test case that communicates via `RTCDataChannels` , inspired by [this example](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample). I pushed the tests to [this repo](https://github.com/maschad/simple-playwright-webrtc-test)  and I can see there is definitely a discrepancy when running on ubuntu vs macOS for webkit, in this case the fill [element handle](https://playwright.dev/docs/api/class-elementhandle#element-handle-fill) doesn't work [on webkit running on ubuntu](https://github.com/maschad/simple-playwright-webrtc-test/actions/runs/5593484361/jobs/10227176721#step:6:47) but [it works on webkit on mac os](https://github.com/maschad/simple-playwright-webrtc-test/actions/runs/5593620301/jobs/10227473291)

I think these types of discrepancies may be related to some errors in tests but it doesn't explain why a firefox or chrome test may produce a false negative, so doubt it's a browser issue.

**Comment by sukunrt** [comment]
Is there any update here? We are adding support for webrtc in go-libp2p and it'd be nice to test interop with js-libp2p. I have pretty much copied the js-libp2p test implementation: https://github.com/libp2p/go-libp2p/pull/2584

**Comment by maschad** [comment]
We will revisit once https://github.com/libp2p/js-libp2p/pull/2074 is merged, it is causing the current [webRTC tests](https://github.com/libp2p/js-libp2p/actions/runs/6365364804/job/17282378573?pr=2097#step:5:2415) to be flaky in js-libp2p
