### ISSUE TITLE
interop: incorrect instructions to run js-libp2p

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#283]
The README claims that js-libp2p can be run using: `npm run test -- -t node`.
That doesn't work:
```
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: Missing script: "test"

To see a list of scripts, run:
  npm run
npm ERR!   in workspace: multidim-interop@1.0.0
npm ERR!   at location: /Users/marten/src/go/src/github.com/libp2p/js-libp2p/interop
npm ERR! Missing script: test

npm ERR! A complete log of this run can be found in: /Users/marten/.npm/_logs/2023-08-28T05_04_05_748Z-debug-0.log
```

Looking at the [ENTRYPOINT of the Dockerfile](https://github.com/libp2p/js-libp2p/blob/1511105774db3c3c7707809b0262e57bdfa544d8/interop/Dockerfile#L14), this should probably be `test:interop:multidim`, but I'm not sure which command line flags would be needed.

**Comment by marten-seemann** [comment]
Running with `test:interop:multidim` fails for different reasons then. I opened https://github.com/libp2p/js-libp2p/issues/1994.

**Comment by MarcoPolo** [comment]
The whole section for Running locally needs to be reworded. It is more like debugging locally

**Comment by MarcoPolo** [comment]
I'm going to close this issue in favor of #282 because they are the same issue. `npm run test -- -t node` is meant to be run within the js test-plans implementation.
