### ISSUE TITLE
multidim-interop: rename to "transport"?

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/test-plans#306]
With the upcoming additional interoperability tests, I was wondering whether we shouldn't rename the existing `multidim-interop` tests to `transport-interop`?

I am also open to other suggestions but I find "multidim" by itself to be too implementation specific. It tells us _how_ we are testing things but not what we are testing. Plus, in the upcoming hole-punching tests, I am using the same "multidim" technique.

Thoughts?

**Comment by mxinden** [comment]
`transport-interop` is fine by me.

**Comment by marten-seemann** [comment]
I agree, in fact I posted pretty much exactly this in my review the blog post: https://pl-strflt.notion.site/Multidimensional-Transport-Interoperability-6d2cc542309e413a930b4ec233b8cc5e.

**Comment by thomaseizinger** [comment]
> I agree, in fact I posted pretty much exactly this in my review the blog post: [pl-strflt.notion.site/Multidimensional-Transport-Interoperability-6d2cc542309e413a930b4ec233b8cc5e](https://pl-strflt.notion.site/Multidimensional-Transport-Interoperability-6d2cc542309e413a930b4ec233b8cc5e).

Great minds think alike :blush: 

Any preferences of `transport-interop` vs `transport-multidim-interop`? Personally, I'd go for the former because it is shorter.

At present state, the hole punching tests only have one dimension (transports). One could imagine that we add a 2nd dimension for a different NAT type perhaps. Hence, I'd argue that all our interop tests have a kind of "multidim" aspect to them so it is redundant to restate that. Lastly, the fact that we are testing different versions against each other might also be seen as a dimension.

**Comment by marten-seemann** [comment]
`transport-interop` sgtm.
