### ISSUE TITLE
feat: automate js-libp2p perf release versions 

### ISSUE THREAD

**Issue by maschad** [libp2p/test-plans#307]
We would like to automate the addition of new js-libp2p versions into perf and multidim interop, would like to see how it performs in different node versions.

**Comment by mxinden** [comment]
See https://github.com/libp2p/test-plans/pull/256 and https://github.com/libp2p/test-plans/pull/294 for inspiration.

**Comment by galargh** [comment]
This has now been automated. See the latest automated PR for this at https://github.com/libp2p/test-plans/pull/360 cc @sukunrt

**Comment by maschad** [comment]
Great work @galargh TY!
