### ISSUE TITLE
Cannot build rust-libp2p during interop test run

### ISSUE THREAD

**Issue by achingbrain** [libp2p/test-plans#343]
I think rust might need updating in the ping interop tests?  It's currently breaking builds.

```
#15 161.2 error: package `libp2p-identity v0.2.8` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.67.0
```

https://github.com/libp2p/js-libp2p/actions/runs/7638820411/job/20810985299?pr=2372

cc @mxinden @thomaseizinger

**Comment by mxinden** [comment]
I believe @thomaseizinger has already been looking into this: https://github.com/libp2p/test-plans/pull/342

**Comment by achingbrain** [comment]
I spotted that but [the build error](https://github.com/libp2p/rust-libp2p/issues/5117) it fixes seems different?  Though I guess the fix is probably going to be the same.

**Comment by thomaseizinger** [comment]
Yeah the underlying issue is I believe a bug in `cargo-chef`: https://github.com/LukeMathWalker/cargo-chef/issues/252

**Comment by achingbrain** [comment]
That's fixed it, thanks!
