### ISSUE TITLE
Add latest js-libp2p versions for transport-interop tests

### ISSUE THREAD

**Issue by sukunrt** [libp2p/test-plans#347]
Currently we are testing against versions v0.45 and v0.46 which are about four months old. We should add the latest versions while we work on automating this step.

**Comment by galargh** [comment]
This has now been automated. You can find the latest automated PR at https://github.com/libp2p/test-plans/pull/359

**Comment by sukunrt** [comment]
This is amazing! Thanks @galargh ❤️
