### ISSUE TITLE
transport-interop: automate adding new versions

### ISSUE THREAD

**Issue by sukunrt** [libp2p/test-plans#348]
It would be great if we can automate adding new go-libp2p versions for transport interop tests. The process at least for go-libp2p is very mechanical and should possible to automate. 

There's a similar issue open for js-libp2p perf tests: https://github.com/libp2p/test-plans/issues/307

@galargh is this something IPDX would be interested in picking up?

**Comment by galargh** [comment]
Sure, that's definitely in our ballpark. We'll prepare a plan/proposal early next week. Thank you for the ping.

**Comment by galargh** [comment]
Quick follow-up, I reached out to Interplanetary Shipyard to check with them if we can schedule this (for Go, JS and Rust) this month. I'll keep you updated.

**Comment by galargh** [comment]
Good news! We've had this piece of work approved 🚀 We'll work on this feature next week. We'll start with finishing up the automation for Go and then, if time permits, we'll move on to getting Rust and JS a similar treatment.
