### ISSUE TITLE
interop test fails to build a branch that was force pushed (missing ref)

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#36]
```
Step 17/30 : RUN echo "Using go proxy: ${GO_PROXY}"     && cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && go mod download
 ---> Running in bb791e47ce99
 ---> Running in ad95548510e6
Using go proxy: https://proxy.golang.org/
 ---> Running in 923053e7879d
go: errors parsing go.mod:
/plan/go.mod:112: replace github.com/libp2p/go-libp2p: version "1e9e60c325404ef[949](https://github.com/libp2p/go-libp2p/runs/8151172207?check_suite_focus=true#step:6:950)8c6424353493490431c86b" invalid: reading https://proxy.golang.org/github.com/libp2p/go-libp2p/@v/1e9e60c325404ef9498c6424353493490431c86b.info: 404 Not Found
	server response: not found: github.com/libp2p/go-libp2p@1e9e60c325404ef9498c6424353493490431c86b: invalid version: unknown revision 1e9e60c325404ef9498c6424353493490431c86b
```

https://github.com/libp2p/go-libp2p/runs/8151172207?check_suite_focus=true

**Comment by laurentsenta** [comment]
On it, thanks for raising this.

Triggered on this branch:
https://github.com/libp2p/go-libp2p/actions/workflows/interop-test.yml?query=branch%3Anoise-early-data2

- https://github.com/libp2p/go-libp2p/runs/8151172207?check_suite_focus=true (Err 1)
  - ref not found: 1e9e60c325404ef9498c6424353493490431c86b
- https://github.com/libp2p/go-libp2p/runs/8151186898?check_suite_focus=true (Err 2)
  - ref not found: 1edade93433784478215996c58b9916282f90739 
- https://github.com/libp2p/go-libp2p/runs/8151214169?check_suite_focus=true (Success)
  - ref found: 8053440c0cc770d895aaa141fa446de1b3f11f1d

**Comment by laurentsenta** [comment]
The proxy couldn't find the commits at build time,
The branch history doesn't contain the other commits: https://github.com/libp2p/go-libp2p/commits/noise-early-data2

Is it correct to assume you force-pushed there a couple of times?

We could cancel the previous run with https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow which would also save GitHub CI resources.

**Comment by marten-seemann** [comment]
> Is it correct to assume you force-pushed there a couple of times?

Yes, I did.

> We could cancel the previous run with https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow which would also save GitHub CI resources.

Sounds reasonable.
