### ISSUE TITLE
js-libp2p tests failing in interop

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#364]
Not sure why yet, I haven't debugged this but I'm seeing every transport interop test with js-libp2p failing:

https://github.com/libp2p/test-plans/actions/runs/9182341165?pr=363
https://github.com/libp2p/test-plans/actions/runs/9182417914?pr=359
https://github.com/libp2p/go-libp2p/actions/runs/9181929857?pr=2807
https://github.com/libp2p/go-libp2p/actions/runs/9180086151?pr=2806
https://github.com/libp2p/go-libp2p/actions/runs/9179966225?pr=2805

I'll update here or in a PR as I learn more.

**Comment by MarcoPolo** [comment]
Works on my machine (of course) with the following steps:

1. Checking out this repo
2. (cd transport-interop/impl/js/v1.6 && make)
3. npm ci
4. ./node_modules/.bin/ts-node testplans.ts -e --name-filter="js-v1.6 x js-v1.6"
5. Save that output to a compose.yml
6. docker compose up

**Comment by diegomrsantos** [comment]
could it be related to this https://github.com/libp2p/js-libp2p/issues/2505 ?

**Comment by diegomrsantos** [comment]
I can't reproduce this issue on my machine either.

**Comment by MarcoPolo** [comment]
Unlikely to be related since it wouldn't explain why it happened suddenly.

I also pulled the exact image used by CI with:
```
curl https://s3.amazonaws.com/libp2p-by-tf-aws-bootstrap/imageCache/8d6bd5587fd7d648c4663358526240cb83225b8f7c4633854c17736b0b55892f-x86_64.tar.gz  | docker image load
```

and it still worked locally. I'm thinking this is something to do with the hosts and maybe the version of tools it's running.

**Comment by MarcoPolo** [comment]
Fixed. See https://github.com/libp2p/test-plans/pull/359#issuecomment-2125963356
