### ISSUE TITLE
rust-libp2p build breaks on master's update

### ISSUE THREAD

**Issue by laurentsenta** [libp2p/test-plans#43]
the worfklow started to fail in go-libp2p, here is an example of a run:
https://github.com/libp2p/go-libp2p/actions/runs/3047048099/jobs/4910594908

Raised by @marten-seemann 

We need to investigate, my first intuition:

Now that we merged: https://github.com/libp2p/test-plans/pull/37
We are using "latest" release and not master.

We expect that when rust release a new version and updates `master`, that won't break other tests (because we only test releases known by `libp2p/test-plans`).

BUT we do use a `master` definition in the Cargo file, this is how we deal with multiple versions:
https://github.com/libp2p/test-plans/blob/520162a1881e7a8196728c3f979debd330cec328/ping/rust/Cargo.toml#L27
That line will break if the package is bumped to version 0.49 because it will try to load the repo and won't find the 0.48 version.

We might need to drop this line and use a rewrite in the `master` group.

**Comment by mxinden** [comment]
> We might need to drop this line and use a rewrite in the `master` group.

Off the top of my head, this sounds reasonable to me.

**Comment by laurentsenta** [comment]
Thanks for the input @mxinden,
this should get the CI back to green, that's my current priority,

Related note: https://github.com/libp2p/rust-libp2p/pull/2813#issuecomment-1242700115
