### ISSUE TITLE
ping/_compositions/rust: Add `v0.49.0` and update features of `master`

### ISSUE THREAD

**Issue by mxinden** [libp2p/test-plans#59]
With https://github.com/libp2p/rust-libp2p/pull/3001 `master` is now `v0.50.0` AND removes the `dns-async-std` etc. features.

This results in test failures, see e.g. https://github.com/libp2p/rust-libp2p/pull/3047.

We need to do the upgrade of `libp2p/test-plans` similar to https://github.com/libp2p/test-plans/pull/41.

Most prominently, we need to update the versions below:

https://github.com/libp2p/test-plans/blob/c71602e88c8a20c6ecc7c18fe1f5b5cf570d3b11/ping/_compositions/rust.toml#L1-L9

and update the `Cargo.toml.

//CC the rust-libp2p team @thomaseizinger @jxs @elenaf9 for visibility and in case one of you wants to pick this up.

**Comment by thomaseizinger** [comment]
Working on this now.
