### ISSUE TITLE
Canonical interop tests & dashboard

### ISSUE THREAD

**Issue by p-shahi** [libp2p/test-plans#62]
A comprehensive and canonical dashboard that is

- [x] generated from a nightly CI run
- [x] hosted in a publicly discoverable site that displays latest test suite results (Pass/Fail/Implemented/Not Implemented/Unimplementable)
- [x] All permutations of libp2p implementations, versions, and supported transports, muxers, & security protocols should be visible.

An enhancement of https://github.com/libp2p/test-plans/issues/55

**Comment by MarcoPolo** [comment]
I think this is done? Closing it, but feel free to reopen if you disagree.

**Comment by BigLep** [comment]
Agreed is done.
One can access the latest dashboard run with the badge https://github.com/libp2p/test-plans .  Example: https://github.com/libp2p/test-plans/actions/runs/4166302313/attempts/1#summary-11307682074

<img width="828" alt="image" src="https://user-images.githubusercontent.com/85411/219736997-2431a326-a2fa-4258-babb-436c3711ba66.png">
