### ISSUE TITLE
Split Rust project into one binary per dependency version

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/test-plans#71]
This should hopefully be more maintainable down the line and help resolve errors such as https://github.com/libp2p/rust-libp2p/actions/runs/3390990380/jobs/5635708451.

**Comment by thomaseizinger** [comment]
Going to start working on this, will put up a draft soon.

**Comment by mxinden** [comment]
Sounds good to me. Thanks @thomaseizinger. Looking forward to reading the draft.
