### ISSUE TITLE
Add secure channel benchmarking test plan

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/test-plans#8]
Several months back I wrote my first testground plan: https://github.com/testground/testground/pull/335 but never quite finished cleaning it up and making it usable. 

Testground has changed a lot since then, so I closed the PR, but it may be useful as a reference. The basic idea is to just transfer a bunch of data between two peers using each kind of crypto channel (secio, tls, noise) and see how long it takes.

**Comment by MarcoPolo** [comment]
We got this now. Closing
