### ISSUE TITLE
add webrtc to logic of ping/rust

### ISSUE THREAD

**Issue by John-LittleBearLabs** [libp2p/test-plans#82]
It should be possible to gain access to transports/webrtc in `testplan_0500.rs`
The goal here is to verify that one _could_ get the test to switch from TCP to WebRTC, not to make sure the automated CI tests do so.

**Comment by mxinden** [comment]
@John-LittleBearLabs would you mind opening a pull request with your changes as a draft? That way we might be able to help you and we can follow the progress.

Is there much more required than replacing the `tcp` here with `webrtc`?

https://github.com/libp2p/test-plans/blob/31a128833da19f1ded62a73296c9e1764d97ac13/ping/rust/src/lib.rs#L48

Note that this will only work with rust-libp2p `v0.50.0`, which has been released last week.

**Comment by John-LittleBearLabs** [comment]
> would you mind opening a pull request with your changes as a draft?

https://github.com/libp2p/test-plans/pull/84

> Is there much more required than replacing the `tcp` here with `webrtc`?

I do believe so. The existing test code doesn't even have the 'webrtc' cargo feature.

> Note that this will only work with rust-libp2p `v0.50.0`, which has been released last week.

Yeah I've been testing in the master config, but knowing that it's been released I should be able to update to depend on the released version directly.
