### ISSUE TITLE
simplify the ping test

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#94]
There's good reasons to have tests that involve `N` nodes, but in the ping test, we're just interested in one-to-one connections. There's significant complexity (synchronization logic) in supporting the general case here, I suggest to cut the ping test down to exactly what we need from that case.

**Comment by p-shahi** [comment]
Don't think this is needed any more since we removed these altogether in https://github.com/libp2p/test-plans/pull/129
